### ISSUE TITLE
Tracking: CAR Mirror

### ISSUE THREAD

**Issue by justincjohnson** [fission-codes/go-car-mirror#1]
This is an attempt at breaking down the work for implementing CAR Mirror.

## Issues
- [x] https://github.com/fission-codes/go-car-mirror/issues/13
- [x] https://github.com/fission-codes/go-car-mirror/issues/10
- [x] https://github.com/fission-codes/go-car-mirror/issues/5
- [x] https://github.com/fission-codes/go-car-mirror/issues/11
- [x] https://github.com/fission-codes/go-car-mirror/issues/7
- [x] https://github.com/fission-codes/go-car-mirror/issues/8
- [x] https://github.com/fission-codes/go-car-mirror/issues/2
- [x] https://github.com/fission-codes/go-car-mirror/issues/4
- [x] https://github.com/fission-codes/go-car-mirror/issues/6
## Notes

Plumbing
- Library / microservice plumbing vs go-ipfs
  - See DSync code for ideas on how to organize, like DSync struct with its various services
  - Think about how the code will look before merging into go-ipfs and after, in case design decisions can avoid extra refactoring work later

- URL parsing
- Developer entry point, starting a session, returning status when all rounds are complete, list of CIDs that could not be fulfilled
  - Push and Pull functions I assume
  - pinOnComplete option?
- Configuration, what do we allow to be configured, in library, in go-ipfs config later
  - Is switching to Bitswap in worst case something that should be handled in this code directly?  Always or configurable?
- Versioning, protocol version
- DSync has to create a plugin for registering a new libp2p protocol, if I read correctly.  I assume we don't need anything like that?  We avoid libp2p entirely?

Security
- Any permission related code needed?  Allow and deny lists?

Observability
- Logging
- Metrics

UX
- Progress?

DAG traversal
- Traverse DAG represented by mutable pointer in local store and construct bloom

Sessions
- Create Session Cache (Hash Set)
- Update Session Cache
- Ending of session
- At least 30s TTL for provider state beyond last sent block

Caches (other than session cacheing?)
- Peer state, metadata about block stores, memoization

Rounds
- Related to sessions
- Details around when to end a round, make next API call

CAR
- Create discrete CAR
- Create streaming CAR (HLS)
...

Cleanup
- No Bloom filter involved, maybe simpler cases to start with
- How often do we cleanup?  Typically not deeply nested.  Peers may switch to Bitswap to fulfill these requests.  What does this mean?

Handling edge cases
- Provider has no blocks
- Straggler cleanup is sort of edge case, and note that straggler cleanup can happen at any round, with bloom filter used on rounds before or after, straggler cleanup helping the process to get "unstuck" such that bloom is useful again
- Anything to think about for GC, corruption, 

Push vs Pull

Any details related to HLS, WSS, impact on code organization to handle streaming and less of a clear boundary between rounds.

**Comment by justincjohnson** [comment]
Since every issue in the repo is part of the initial implementation, I'm going to ditch the tracking issue and move my notes elsewhere.
